import type { FeedPost } from "./types";

export const FEED_POSTS: FeedPost[] = [
  {
    id: "f1",
    handle: "@freedom.machine",
    avatar: "🤑",
    color: "debt",
    kind: "scam",
    body: "I made $8,000 THIS WEEK with an AI trading bot while I slept. DM the word FREEDOM and I'll add you to the group. Spots almost gone.",
    redFlags: [
      "Guaranteed huge returns ('$8,000 a week')",
      "Urgency: 'spots almost gone'",
      "Wants you to DM a magic keyword",
      "No verifiable track record or registration",
    ],
    isScam: true,
    onAccept: { cash: -200, stress: 12, freedom: -6 },
    onReport: { skill: 5, freedom: 4, stress: -2 },
  },
  {
    id: "f2",
    handle: "@subscribe.pls",
    avatar: "📺",
    color: "risk",
    kind: "pressure",
    body: "New premium tier just dropped. Only $34/month. No big deal, it's basically a coffee (per week) (that you buy every day) (forever).",
    redFlags: [
      "'Only $X/month' framing hides the yearly total ($408/yr)",
      "Compares a recurring cost to a one-time treat",
      "No clear added value for the price",
    ],
    isScam: false,
    onAccept: { cash: -34, stress: 2, freedom: -3 },
    onReport: { skill: 2, freedom: 1 },
  },
  {
    id: "f3",
    handle: "@bali.or.nothing",
    avatar: "🌴",
    color: "social",
    kind: "pressure",
    body: "Everyone's going to Bali next month. You coming or not?? Don't be the broke friend who 'can't make it' again.",
    redFlags: [
      "Social pressure + shaming ('broke friend')",
      "Manufactured FOMO",
      "No mention of what it actually costs",
    ],
    isScam: false,
    onAccept: { cash: -900, debt: 600, stress: -6, freedom: -7 },
    onReport: { skill: 2, freedom: 3, stress: -1 },
  },
  {
    id: "f4",
    handle: "@official.scholarships",
    avatar: "🎓",
    color: "debt",
    kind: "scam",
    body: "CONGRATULATIONS! You've been selected for a $5,000 scholarship. Simply pay the $39 processing fee to release your funds today.",
    redFlags: [
      "Real scholarships never charge a fee to receive money",
      "You never applied for this",
      "Urgency + official-sounding name",
    ],
    isScam: true,
    onAccept: { cash: -39, stress: 8, freedom: -4 },
    onReport: { skill: 6, freedom: 4, stress: -2 },
  },
  {
    id: "f5",
    handle: "@coin.wizard",
    avatar: "🪙",
    color: "skill",
    kind: "scam",
    body: "This coin is about to EXPLODE — don't ask questions, just ape in before 6pm. NFA but you'll thank me. I'm literally giving you alpha.",
    redFlags: [
      "'Don't ask questions' = the biggest question",
      "Hard deadline ('before 6pm')",
      "'NFA' disclaimer used as a shield",
      "Hype with zero fundamentals",
    ],
    isScam: true,
    onAccept: { cash: -150, debt: 0, stress: 10, freedom: -5 },
    onReport: { skill: 5, freedom: 4 },
  },
  {
    id: "f6",
    handle: "@payday.express",
    avatar: "🧛",
    color: "debt",
    kind: "offer",
    body: "Short on cash? Get $300 in MINUTES. No credit check! The Payday Vampire smiles like this is charity. (It is 391% APR.)",
    redFlags: [
      "'No credit check' usually means brutal interest",
      "Triple-digit APR buried in the fine print",
      "Targets people in a cash crunch",
    ],
    isScam: false,
    onAccept: { cash: 300, debt: 480, stress: 14, freedom: -8 },
    onReport: { skill: 4, freedom: 3 },
  },
];
